x = linspace(-100,100,100);
y1 = x;
y2 = -x./36;

subplot(1,3,1);
hold on;
plot(x,y1, 'r');
plot(x,y2, 'r');
title('Cone for \{(x, y)| x = y || x = -36y \}');
xlabel('x');
ylabel('y');
subplot(1,3,2);
scatter(0, 0, 'b');
title('Dual of Cone for \{(x, y)| x = y || x = -36y \}');
xlabel('x');
ylabel('y');
subplot(1,3,3);
set(gca, 'color', 'g');
title('Dual of Dual of Cone for \{(x, y)| x = y || x = -36y \}');
xlabel('x');
ylabel('y');